# Generated by Django 3.2.3 on 2021-06-09 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsdbRaw',
            fields=[
                ('job_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('raw_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('vendor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobsDetail',
            fields=[
                ('job_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('page_url', models.URLField()),
                ('salary_min', models.FloatField(null=True)),
                ('salary_max', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=4, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField()),
                ('job_description', models.TextField()),
                ('job_requirements', models.TextField()),
                ('benefits', models.TextField()),
                ('industry', models.CharField(max_length=255)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.vendors')),
            ],
        ),
    ]
