# Generated by Django 3.2.3 on 2021-06-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
