# Generated by Django 3.2.3 on 2021-06-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20210609_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsdetail',
            name='currency',
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='jobsdetail',
            name='salary_max',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='jobsdetail',
            name='salary_min',
            field=models.FloatField(default=None),
        ),
    ]
