# Generated by Django 3.2.3 on 2021-06-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0004_auto_20210613_1745"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobsdetail",
            name="job_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
