# Generated by Django 3.2.5 on 2021-07-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0006_auto_20210617_0937"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobsdetail",
            name="benefits",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="jobsdetail",
            name="job_description",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="jobsdetail",
            name="job_requirements",
            field=models.JSONField(),
        ),
    ]
