# Generated by Django 3.2.3 on 2021-05-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
