# Generated by Django 3.2.5 on 2021-07-13 06:14

from django.db import migrations


def populate_vendor(apps, schema_editor):
    ## the parameters are supplied by RunPython
    Websites = apps.get_model('scraper', 'Websites')
    Websites.objects.create(name='jobsdb', url='https://www.jobsdb.com')


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_websites_name'),
    ]

    operations = [
        migrations.RunPython(populate_vendor),
    ]
