JOBSDB_EXPECTED_DATA = {
    "job_id": "300003002376339",
    "page_url": "https://th.jobsdb.com/th/en/job/job-300003002376339",
    "salary_max": None,
    "salary_min": None,
    "currency": "THB",
    "job_title": "IT Staff/เจ้าหน้าที่ IT",
    "company": "SATO KOKI (THAILAND) CO., LTD.",
    "post_date": "2021-06-08 17:03:36",
    "job_description": [
        "สามารถใช้งาน Program PostgreSQL ได้",
        "สามารถใช้งาน Program Open ERP (V7) ปัจจุบันคือOdoo",
        "สามารถใช้งานระบบปฎิบติการ Ubuntu Server ได้",
    ],
    "job_requirements": [
        "ดูแลงานระบบ ERP\xa0 ระบบข้อมูลการผลิตของบริษัทฯ",
        "ไม่จำกัดเพศ\xa0\xa0",
        "จบการศึกษา ระดับปริญญาตรี สาขาคอมพิวเตอร์,IT หรือที่เกี่ยวข้อง",
        "มีประสบการณ์ไม่น้อยกว่า 1 ปี",
        "สามารถใช้งาน Program PostgreSQL ได้",
        "สามารถใช้งาน Program Open ERP (V7) ปัจจุบันคือ Odoo ได้",
        "สามารถใช้งานระบบปฎิบติการ Ubuntu Server ได้",
        "มีความรู้ในการใช้ภาษา Python ได้",
        "มีความรู้ในการใช้ Microsoft Office",
    ],
    "benefits": [
        "Free shuttle bus",
        "Life insurance",
        "Overtime pay",
        "Performance bonus",
    ],
    "industry": "Electronics/Electrical Equipment",
}

JOBSDB_RAW_DATA = {'data': {'jobDetail': {'id': '300003002376339',
    'pageUrl': 'https://th.jobsdb.com/th/en/job/job-300003002376339',
    'jobTitleSlug': None,
    'applyUrl': {'url': 'https://th.jobsdb.com/th/en/job/300003002376339/apply-preview',
     'isExternal': False},
    'isExpired': False,
    'isConfidential': False,
    'isClassified': False,
    'accountNum': 300301094,
    'advertisementId': '300003002376339',
    'subAccount': None,
    'showMoreJobs': None,
    'adType': 'standout',
    'header': {'banner': {'bannerUrls': {'large': 'https://image-service-cdn.seek.com.au/cc25c974d7d175aeb84549e6d0a7ed171a11446e/a868bcb8fbb284f4e8301904535744d488ea93c1'}},
     'salary': {'max': None,
      'min': None,
      'type': 'monthly',
      'extraInfo': None,
      'currency': 'THB',
      'isVisible': False},
     'logoUrls': {'small': None, 'medium': None, 'large': None, 'normal': ''},
     'jobTitle': 'IT Staff/เจ้าหน้าที่ IT',
     'company': {'name': 'SATO KOKI (THAILAND) CO., LTD.',
      'url': '',
      'slug': 'sato-koki-thailand-co-ltd',
      'advertiserId': 'th300301094'},
     'review': None,
     'expiration': 22,
     'postedDate': '7 hours ago',
     'postedAt': '2021-06-08T17:03:36Z',
     'isInternship': False},
    'companyDetail': {'companyWebsite': '',
     'companySnapshot': {'avgProcessTime': '',
      'registrationNo': '',
      'employmentAgencyPersonnelNumber': None,
      'employmentAgencyNumber': None,
      'telephoneNumber': None,
      'workingHours': None,
      'website': None,
      'facebook': None,
      'size': '',
      'dressCode': None,
      'nearbyLocations': ''},
     'companyOverview': {'html': '<p><span style="font-family:arial,helvetica,sans-serif;font-size:10pt;color:#000000">Since its founding in 1957, Sato Koki has worked as a top manufacturer of technology, centering on pipe processing and cutting. In particular, we focused on the manufacture\n of refrigeration cycle parts used for air conditioners, etc. We acquired various processing expertise and accumulation of high level of technology by trading with the air conditioner industry, which is undergoing rapid changes such as energy saving and compactification.\n In particular, we have successfully mass-produced bulge processing using tap water by combining our technical capabilities for bulge processing. Today, the range of applied technology such as medium / large air conditioning equipment, refrigeration cycle parts\n such as eco hot water supply, refrigerator, vending machine and piping parts for residential equipment equipment are expanding. We are actively expanding overseas and establish subsidiaries in China and Thailand to provide overseas customers with quality parts\n and technical aspects at the same level as those made in Japan and we strive to satisfy them. In Thailand, we have grand opening a new factory in Lat Lum Kaew District. Pathumthani Province on October 2020, we are recruiting talented and high potential employees\n to join us.</span></p>'},
     'videoUrl': None,
     'companyPhotos': []},
    'jobDetail': {'summary': ['สามารถใช้งาน Program PostgreSQL ได้',
      'สามารถใช้งาน Program Open ERP (V7) ปัจจุบันคือOdoo',
      'สามารถใช้งานระบบปฎิบติการ Ubuntu Server ได้'],
     'jobDescription': {'html': '<span style="text-decoration:underline;font-family:arial,helvetica,sans-serif;font-size:10pt;color:#000000"><strong>ลักษณะงาน\xa0</strong></span><br /><br /><ul><li><span style="font-family:arial,helvetica,sans-serif;font-size:10pt;color:#000000">ดูแลงานระบบ ERP\xa0 ระบบข้อมูลการผลิตของบริษัทฯ<br /></span></li></ul><span style="font-family:arial,helvetica,sans-serif;font-size:10pt;color:#000000"><strong><span style="text-decoration:underline">คุณสมบัติ</span></strong></span><br /><ul><li><span style="font-family:arial,helvetica,sans-serif;font-size:10pt">ไม่จำกัดเพศ\xa0\xa0</span></li><li><span style="font-family:arial,helvetica,sans-serif;font-size:10pt">จบการศึกษา ระดับปริญญาตรี สาขาคอมพิวเตอร์,IT หรือที่เกี่ยวข้อง</span></li><li><span style="font-family:arial,helvetica,sans-serif;font-size:10pt">มีประสบการณ์ไม่น้อยกว่า 1 ปี</span></li><li><span style="font-family:arial,helvetica,sans-serif;font-size:10pt">สามารถใช้งาน Program PostgreSQL ได้</span></li><li><span style="font-family:arial,helvetica,sans-serif;font-size:10pt">สามารถใช้งาน Program Open ERP (V7) ปัจจุบันคือ Odoo ได้</span></li><li><span style="font-family:arial,helvetica,sans-serif;font-size:10pt">สามารถใช้งานระบบปฎิบติการ Ubuntu Server ได้</span></li><li><span style="font-family:arial,helvetica,sans-serif;font-size:10pt">มีความรู้ในการใช้ภาษา Python ได้</span></li><li><span style="font-family:arial,helvetica,sans-serif;font-size:10pt">มีความรู้ในการใช้ Microsoft Office</span></li></ul>'},
     'jobRequirement': {'careerLevel': 'Entry Level',
      'yearsOfExperience': '1 year',
      'qualification': 'Degree',
      'fieldOfStudy': None,
      'industryValue': {'value': 'electronic',
       'label': 'Electronics/Electrical Equipment'},
      'skills': None,
      'employmentType': 'Full Time, Permanent',
      'languages': None,
      'postedDate': '7 hours ago',
      'closingDate': '2021-07-02T00:00:00Z',
      'jobFunctionValue': [{'code': 131,
        'name': 'Information Technology (IT)',
        'children': None},
       {'code': 132,
        'name': 'Application Specialist - Software',
        'children': None},
       {'code': 139, 'name': 'Support', 'children': None}],
      'benefits': ['Free shuttle bus',
       'Life insurance',
       'Overtime pay',
       'Performance bonus']},
     'whyJoinUs': None},
    'location': [{'location': 'Ladlumkaew',
      'locationId': '63',
      'omnitureLocationId': '63'}],
    'sourceCountry': 'th'}}}
